version: '3'
services:
    postgres:
        image: postgres:14
        container_name: auth-sequelize
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - ${DB_PORT}:5432
    postgres-test:
        image: postgres:14
        container_name: auth-sequelize-test
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
            POSTGRES_USER: ${DB_TEST_USERNAME}
            POSTGRES_DB: ${DB_TEST_DATABASE}
        ports:
            - ${DB_TEST_PORT}:5432
